[package]
name = "<name>"
authors = ["<author>"]
version = "<version>"
edition = "<edition>"

[dependencies]
nx = { git = "https://github.com/aarch64-switch-rs/nx" }

[package.metadata.nx.nro]
nacp = { name = "<name>", author = "<author>", version = "<version>" }