[package]
name = "cargo-nx"
version = "0.1.0"
authors = ["XorTroll"]
license = "MIT"
homepage = "https://github.com/aarch64-switch-rs/cargo-nx/"
repository = "https://github.com/aarch64-switch-rs/cargo-nx/"
edition = "2018"
description = "Cargo subcommand to simplify building Nintendo Switch projects"

[dependencies]
scroll = { version = "0.10" }
serde = "1"
serde_derive = "1"
serde_json = "1"
cargo_metadata = { version = "0.12.0" }
cargo-toml2 = { version = "1.3.2" }
linkle = { git = "https://github.com/XorTroll/linkle", branch = "npdm" }